name:                youtube-gtk
version:             0.1.0.0
github:              "githubuser/youtube-gtk"
license:             GPL-3
author:              ""
maintainer:          ""
copyright:           ""
description:         Please see the README on GitHub

dependencies:
- base >= 4.7 && < 5
- directory
- gi-gtk == 3.0.*
- gi-gdk
- gi-gtk-hs
- haskell-gi-base
- process
- unix
- text
- aeson
- aeson-casing
- servant
- servant-server
- lens-aeson
- req
- mtl
- transformers
- hashmap
- bytestring
- json
- aeson-schemas
- http-client
- pretty-simple
- aeson-casing
- utf8-string
- time
# - gi-pango
- gi-atk
- gi-gobject
- gi-gio
- gi-glib
- gi-pango
- gi-gdk
- gi-gdkpixbuf
- gi-gtk
- gi-cairo

- haskell-gi
# - gi-gstbase
# - gi-gst
# - gi-gstvideo
# - MissingH

library:
  source-dirs: src

executables:
  youtube-gtk:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - youtube-gtk

tests:
  youtube-gtk-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - youtube-gtk
